# Generated by Django 5.0.6 on 2024-05-27 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_loan_bookfk_loan_bookfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bookFK',
            field=models.ManyToManyField(related_name='bookLoan', to='app.book'),
        ),
    ]
